#!/usr/bin/env bash

DIR="$(dirname "${BASH_SOURCE[0]}")"
DIR="$(realpath "${DIR}")"

source "$DIR/.env"

path="$PYKE_DEPLOY_PATH"
repo="$PYKE_REPO_URL"
app="$PYKE_APP"

echo $path

cd $path

git remote update
status="$(git status | grep "up to date")"

if [ ! -z "$status" ]; then
  echo "[Pyke] No changes detected, nothing to pull."
  exit 0
fi

echo "[Pyke] Changes detected, pulling via git."

git pull
npm run postdeploy
